### ISSUE TITLE
http://docs.python-maya.org/ is down

### ISSUE THREAD

**Issue by pzelnip** [kennethreitz/maya#85] opened 2017-06-14 16:12 UTC
Going to http://docs.python-maya.org/ or the bare domain python-maya.org results in a DNS resolution error.

**Comment by timofurrer** [comment] 2017-06-15 14:51
Duplicate of #83

**Comment by markfink** [comment] 2017-06-20 06:46
+1
docu link from the header is broken

**Comment by kennethreitz** [comment] 2017-06-20 21:11
i don't think this was ever setup, yet.

**Comment by kennethreitz** [comment] 2017-06-20 21:11
i'll remove the link for now

**Comment by thornycrackers** [comment] 2017-11-24 20:39
Is this getting set up any time soon?

**Comment by timofurrer** [comment] 2018-03-18 12:53
I'm going to close those in favor of #56 . 
Once there is a solid documentation I guess we can put it up on http://docs.python-maya.org/

**Closed by timofurrer** 2018-03-18 12:53 UTC
